### ISSUE TITLE
Support parsing to tuples?

### ISSUE THREAD

**Issue by RandomString123** [RandomString123/FWF.jl#14]
@bkamins I think in your interface you supported parsing into a tuple?  Would it be difficult to implement that here?  Do you think we should?

It might be useful to have as right now the only thing that a FWF file can be loaded into is a DataFrame.  Granted that might be the most popular destination, but it might not be the only one users would want to load a file into.

**Comment by bkamins** [comment]
I had output as `NamedTuple` because I wanted to avoid dependency on external packages.

Your design depends on *DataStreams.jl* and if I understand it correctly supports sinks that are defined there, not only `DataFrame`. I thought this was what you wanted.

Of course we can add more custom sinks, but maybe then you should consider committing a PR to *DataStreams.jl* so that any package depending on it has a support for a format you need?

**Comment by RandomString123** [comment]
I was thinking how a future user might use the parser beyond DataFrames and functionality they might find useful.  

But, implementing a bunch of different interfaces does seem the wrong solution.   Using Sink in DataStreams is probably the best way to have a universal output and if we wanted to be able to output to a NamedTuple then the best way to do that would be to add a Sink interface to named tuple (if there is not one already). 

So this isn't an us issue...closing.
